-- Foundry: Consolidated SQLite schema
-- Converted from PostgreSQL migrations 001–008

PRAGMA foreign_keys = ON;

-- ============================================
-- REPO
-- ============================================

CREATE TABLE IF NOT EXISTS repo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    clone_url TEXT NOT NULL,
    default_image TEXT NOT NULL DEFAULT 'ubuntu:24.04',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- 002
    description TEXT,
    last_build_at TEXT,
    build_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    -- 003
    github_id INTEGER,
    full_name TEXT,
    html_url TEXT,
    ssh_url TEXT,
    private BOOLEAN DEFAULT 0,
    default_branch TEXT DEFAULT 'main',
    language TEXT,
    topics TEXT,              -- JSON array, e.g. '["rust","ci"]'
    updated_at TEXT,
    -- 006
    config_json TEXT,         -- JSON object
    triggers_branches TEXT DEFAULT '["main","master"]',  -- JSON array
    triggers_pull_requests BOOLEAN DEFAULT 1,
    triggers_pr_target_branches TEXT,                     -- JSON array
    UNIQUE(owner, name)
);

-- ============================================
-- RUNNER
-- ============================================

CREATE TABLE IF NOT EXISTS runner (
    id TEXT PRIMARY KEY,      -- UUID generated by application
    name TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',  -- JSON array
    cpu INTEGER,
    memory_mb INTEGER,
    gpu INTEGER DEFAULT 0,
    arch TEXT NOT NULL DEFAULT 'x86_64',
    status TEXT NOT NULL DEFAULT 'offline' CHECK (status IN ('online', 'offline', 'busy')),
    last_heartbeat TEXT,
    registered_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================
-- SCHEDULED_JOB
-- ============================================

CREATE TABLE IF NOT EXISTS scheduled_job (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id INTEGER NOT NULL REFERENCES repo(id) ON DELETE CASCADE,
    cron_expression TEXT NOT NULL,
    branch TEXT NOT NULL DEFAULT 'main',
    timezone TEXT DEFAULT 'UTC',
    enabled BOOLEAN NOT NULL DEFAULT 1,
    last_run_at TEXT,
    next_run_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(repo_id, branch)
);

-- ============================================
-- JOB
-- ============================================

CREATE TABLE IF NOT EXISTS job (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id INTEGER NOT NULL REFERENCES repo(id),
    git_sha TEXT NOT NULL,
    git_ref TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    started_at TEXT,
    finished_at TEXT,
    claimed_by TEXT,
    claim_token TEXT,
    -- 002
    commit_message TEXT,
    commit_author TEXT,
    commit_url TEXT,
    -- 003: push event metadata
    before_sha TEXT,
    compare_url TEXT,
    commits_count INTEGER,
    distinct_commits_count INTEGER,
    forced BOOLEAN DEFAULT 0,
    deleted BOOLEAN DEFAULT 0,
    created BOOLEAN DEFAULT 0,
    -- 003: pusher / sender
    pusher_name TEXT,
    pusher_email TEXT,
    sender_id INTEGER,
    sender_login TEXT,
    sender_avatar_url TEXT,
    sender_type TEXT,
    -- 003: head commit extended
    commit_author_email TEXT,
    commit_timestamp TEXT,
    commit_tree_id TEXT,
    -- 003: committer
    committer_name TEXT,
    committer_email TEXT,
    committer_username TEXT,
    -- 003: file lists (JSON arrays)
    files_added TEXT,
    files_modified TEXT,
    files_removed TEXT,
    -- 003: installation / check run
    installation_id INTEGER,
    check_run_id INTEGER,
    check_suite_id INTEGER,
    -- 003: build metadata
    docker_image TEXT,
    exit_code INTEGER,
    error_message TEXT,
    -- 003: agent metadata
    agent_version TEXT,
    agent_hostname TEXT,
    -- 004: PR / rerun fields
    trigger_type TEXT NOT NULL DEFAULT 'push'
        CHECK (trigger_type IN ('push', 'pull_request', 'manual', 'scheduled')),
    pr_number INTEGER,
    pr_title TEXT,
    pr_url TEXT,
    pr_author TEXT,
    pr_author_avatar TEXT,
    base_ref TEXT,
    base_sha TEXT,
    parent_job_id INTEGER REFERENCES job(id),
    timeout_secs INTEGER DEFAULT 1800,
    timed_out BOOLEAN DEFAULT 0,
    -- 005: stages / metrics / scheduling
    scheduled_job_id INTEGER REFERENCES scheduled_job(id),
    stages_json TEXT,         -- JSON object
    metrics_json TEXT,        -- JSON object
    -- 007: runner
    runner_id TEXT REFERENCES runner(id) ON DELETE SET NULL,
    runner_requirements TEXT   -- JSON object
);

-- ============================================
-- JOB_LOG
-- ============================================

CREATE TABLE IF NOT EXISTS job_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id),
    ts TEXT NOT NULL DEFAULT (datetime('now')),
    line TEXT NOT NULL
);

-- ============================================
-- JOB_COMMIT
-- ============================================

CREATE TABLE IF NOT EXISTS job_commit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    sha TEXT NOT NULL,
    tree_id TEXT,
    message TEXT,
    author_name TEXT,
    author_email TEXT,
    author_username TEXT,
    committer_name TEXT,
    committer_email TEXT,
    committer_username TEXT,
    timestamp TEXT,
    url TEXT,
    added TEXT,               -- JSON array
    modified TEXT,            -- JSON array
    removed TEXT,             -- JSON array
    distinct_commit BOOLEAN DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(job_id, sha)
);

-- ============================================
-- WEBHOOK_EVENT
-- ============================================

CREATE TABLE IF NOT EXISTS webhook_event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type TEXT NOT NULL,
    delivery_id TEXT,
    signature_valid BOOLEAN DEFAULT 1,
    payload TEXT NOT NULL,    -- JSON object
    processed BOOLEAN DEFAULT 0,
    job_id INTEGER REFERENCES job(id),
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================
-- JOB_ARTIFACT
-- ============================================

CREATE TABLE IF NOT EXISTS job_artifact (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    path TEXT NOT NULL,
    size_bytes INTEGER,
    content_type TEXT,
    sha256 TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================
-- JOB_METRIC
-- ============================================

CREATE TABLE IF NOT EXISTS job_metric (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    metric_name TEXT NOT NULL,
    metric_value REAL NOT NULL,
    unit TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================
-- JOB_STAGE
-- ============================================

CREATE TABLE IF NOT EXISTS job_stage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'running', 'success', 'failed', 'skipped')),
    stage_order INTEGER NOT NULL DEFAULT 0,
    command TEXT,
    image TEXT,
    started_at TEXT,
    finished_at TEXT,
    duration_ms INTEGER,
    exit_code INTEGER,
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(job_id, name)
);

-- ============================================
-- STAGE_LOG
-- ============================================

CREATE TABLE IF NOT EXISTS stage_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stage_id INTEGER NOT NULL REFERENCES job_stage(id) ON DELETE CASCADE,
    line TEXT NOT NULL,
    ts TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================
-- JOB_METRICS
-- ============================================

CREATE TABLE IF NOT EXISTS job_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    clone_duration_ms INTEGER,
    build_duration_ms INTEGER,
    test_duration_ms INTEGER,
    deploy_duration_ms INTEGER,
    total_duration_ms INTEGER,
    image_size_bytes INTEGER,
    cache_hit BOOLEAN DEFAULT 0,
    artifact_size_bytes INTEGER,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(job_id)
);

-- ============================================
-- INDEXES
-- ============================================

-- repo
CREATE INDEX IF NOT EXISTS idx_repo_owner_name ON repo(owner, name);
CREATE INDEX IF NOT EXISTS idx_repo_github_id ON repo(github_id) WHERE github_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_repo_triggers ON repo(id) WHERE triggers_branches IS NOT NULL;

-- runner
CREATE UNIQUE INDEX IF NOT EXISTS idx_runner_name_unique ON runner(name);
CREATE INDEX IF NOT EXISTS idx_runner_status ON runner(status);
CREATE INDEX IF NOT EXISTS idx_runner_tags ON runner(tags);

-- scheduled_job
CREATE INDEX IF NOT EXISTS idx_scheduled_job_next_run ON scheduled_job(next_run_at) WHERE enabled = 1;

-- job
CREATE INDEX IF NOT EXISTS idx_job_status_created ON job(status, created_at) WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS idx_job_repo_id ON job(repo_id);
CREATE INDEX IF NOT EXISTS idx_job_created_at ON job(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_sender_login ON job(sender_login);
CREATE INDEX IF NOT EXISTS idx_job_pusher_name ON job(pusher_name);
CREATE INDEX IF NOT EXISTS idx_job_git_ref ON job(git_ref);
CREATE INDEX IF NOT EXISTS idx_job_check_run ON job(check_run_id) WHERE check_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_job_repo_status_created ON job(repo_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_finished ON job(finished_at DESC) WHERE finished_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_job_pr_number ON job(repo_id, pr_number) WHERE pr_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_job_parent ON job(parent_job_id) WHERE parent_job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_job_runner_id ON job(runner_id);

-- job_log
CREATE INDEX IF NOT EXISTS idx_job_log_job_id ON job_log(job_id, ts);

-- job_commit
CREATE INDEX IF NOT EXISTS idx_job_commit_job_id ON job_commit(job_id);
CREATE INDEX IF NOT EXISTS idx_job_commit_sha ON job_commit(sha);

-- webhook_event
CREATE INDEX IF NOT EXISTS idx_webhook_event_type ON webhook_event(event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_event_delivery ON webhook_event(delivery_id);

-- job_artifact
CREATE INDEX IF NOT EXISTS idx_job_artifact_job_id ON job_artifact(job_id);

-- job_metric
CREATE INDEX IF NOT EXISTS idx_job_metric_job_id ON job_metric(job_id);
CREATE INDEX IF NOT EXISTS idx_job_metric_name ON job_metric(metric_name, created_at DESC);

-- job_stage
CREATE INDEX IF NOT EXISTS idx_job_stage_job_id ON job_stage(job_id);

-- stage_log
CREATE INDEX IF NOT EXISTS idx_stage_log_stage_id ON stage_log(stage_id);

-- job_metrics
CREATE INDEX IF NOT EXISTS idx_job_metrics_job_id ON job_metrics(job_id);
